"use client";
import {useEffect,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Msg={id:string;sender_id:string;message_type:string;body:string|null;created_at:string};
export default function ChatRoom({conversationId,userId,initialMessages}:{conversationId:string;userId:string;initialMessages:Msg[]}){
 const [messages,setMessages]=useState(initialMessages),[body,setBody]=useState(""),[sending,setSending]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(""),[imageUrls,setImageUrls]=useState<Record<string,string>>({});
 const bottom=useRef<HTMLDivElement>(null); const sb=createClient();
 useEffect(()=>{const ch=sb.channel("messages:"+conversationId).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:"conversation_id=eq."+conversationId},p=>setMessages(x=>x.some(m=>m.id===p.new.id)?x:[...x,p.new as Msg])).subscribe();return()=>{sb.removeChannel(ch)}},[conversationId]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 useEffect(()=>{let cancelled=false;async function load(){for(const m of messages.filter(m=>m.message_type==="image")){if(cancelled||imageUrls[m.id])continue;const {data}=await sb.from("message_attachments").select("storage_path").eq("message_id",m.id).maybeSingle();if(data){const {data:u}=await sb.storage.from("plunge-messages").createSignedUrl(data.storage_path,3600);if(u&&!cancelled)setImageUrls(x=>({...x,[m.id]:u.signedUrl}))}}}load();return()=>{cancelled=true}},[messages]);
 async function send(e:React.FormEvent){e.preventDefault();const text=body.trim();if(!text||sending)return;setSending(true);setError("");setBody("");const {error}=await sb.from("messages").insert({conversation_id:conversationId,sender_id:userId,message_type:"text",body:text});if(error){setBody(text);setError(error.message)}setSending(false)}
 async function sendImage(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;e.target.value="";if(!["image/jpeg","image/png","image/webp","image/gif"].includes(file.type)){setError("Use JPG, PNG, WebP, or GIF.");return}if(file.size>25*1024*1024){setError("Maximum image size is 25 MB.");return}setUploading(true);setError("");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=conversationId+"/"+userId+"/"+crypto.randomUUID()+"-"+safe;const up=await sb.storage.from("plunge-messages").upload(path,file,{contentType:file.type,upsert:false});if(up.error){setError(up.error.message);setUploading(false);return}const msg=await sb.from("messages").insert({conversation_id:conversationId,sender_id:userId,message_type:"image"}).select("id").single();if(msg.error){await sb.storage.from("plunge-messages").remove([path]);setError(msg.error.message);setUploading(false);return}const att=await sb.from("message_attachments").insert({message_id:msg.data.id,storage_path:path,mime_type:file.type,file_size_bytes:file.size});if(att.error){await sb.from("messages").delete().eq("id",msg.data.id);await sb.storage.from("plunge-messages").remove([path]);setError(att.error.message);setUploading(false);return}const {data:u}=await sb.storage.from("plunge-messages").createSignedUrl(path,3600);if(u)setImageUrls(x=>({...x,[msg.data.id]:u.signedUrl}));setUploading(false)}
 return <section className="chat-shell"><div className="chat-heading"><div><span className="eyebrow">PRIVATE CHAT</span><h1>Conversation</h1></div></div><div className="messages">{messages.map(m=><div className={"message "+(m.sender_id===userId?"mine":"theirs")} key={m.id}>{m.message_type==="image"?(imageUrls[m.id]?<img className="chat-image" src={imageUrls[m.id]} alt="Shared image"/>:<span>Image…</span>):m.body}</div>)}<div ref={bottom}/>{!messages.length&&<p className="chat-empty">Say hello. 👋</p>}</div>{error&&<div className="error-box">{error}</div>}<form className="chat-composer" onSubmit={send}><label className="attach-button">{uploading?"…":"＋"}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={sendImage} disabled={uploading||sending}/></label><input value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a message…" maxLength={4000}/><button className="primary-button" disabled={sending||uploading||!body.trim()}>{sending?"…":"Send"}</button></form></section>
}