"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
type Props={data:any;userId:string};
export default function PublicProfile({data}:Props){
 const p=data.profile, [busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[reason,setReason]=useState("other"),[reporting,setReporting]=useState(false),router=useRouter();
 const photo=(data.photos?.[0]?.storage_path)?`https://pukwdnexknvspljqyvlk.supabase.co/storage/v1/object/public/plunge-profiles/${data.photos[0].storage_path}`:null;
 async function like(){setBusy(true);const {data:r,error}=await createClient().rpc("like_profile",{target_user_id:p.id});if(error)setMsg(error.message);else{const matched=Array.isArray(r)?r[0]?.matched:r?.matched;setMsg(matched?"It’s a match! 🎉":"Like sent.");}setBusy(false)}
 async function block(){const {error}=await createClient().rpc("block_user",{target_user_id:p.id});if(error)setMsg(error.message);else router.push("/home")}
 async function report(){const {error}=await createClient().rpc("report_user",{target_user_id:p.id,report_reason:reason,report_details:null});setMsg(error?error.message:"Report submitted.");setReporting(false)}
 return <section className="profile-shell public-profile"><div className="public-profile-hero">{photo?<img className="public-profile-photo" src={photo} alt={p.display_name+" profile"}/>:<div className="public-profile-avatar">{p.display_name?.slice(0,1).toUpperCase()}</div>}<div><span className="eyebrow">PLUNGE PROFILE</span><h1>{p.display_name}, {data.age}</h1><p className="profile-location">{p.city}, {p.state} · {p.gender}</p></div></div><p className="profile-bio">{p.bio||"No bio yet."}</p><div className="interest-preview left">{(data.interests||[]).map((i:string)=><span key={i}>{i}</span>)}</div><div className="public-profile-actions"><button className="primary-button" disabled={busy} onClick={like}>{busy?"…":"♥ Like"}</button><button onClick={()=>setReporting(v=>!v)}>Report</button><button onClick={block}>Block</button></div>{reporting&&<div className="report-panel"><select value={reason} onChange={e=>setReason(e.target.value)}><option value="other">Other</option><option value="harassment">Harassment</option><option value="spam">Spam</option><option value="scam">Scam</option><option value="fake_profile">Fake profile</option><option value="inappropriate_image">Inappropriate image</option><option value="threat">Threat</option><option value="underage_concern">Underage concern</option></select><button onClick={report}>Submit report</button></div>}{msg&&<div className="success-box">{msg}</div>}</section>;
}